/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-18 09:58:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.service.CartService;

public final class dang_005fky_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.service.CartService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"bootstrap-5.3.2-dist/css/bootstrap-grid.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"bootstrap-5.3.2-dist/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"bootstrap-5.3.2-dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"fontawesome-free-6.4.2-web/css/all.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/menu_footer.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/dang_nhap_va_dang_ky.css\">\r\n");
      out.write("    <link rel=\"icon\" href=\"logo_icon.png\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"jquery/jquery-3.7.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"jquery/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <title>Đăng ký</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header id=\"menu\">\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg pb-0\">\r\n");
      out.write("        <div class=\"container-xxl m-md-auto mt-2\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"logo col-lg-2 col-md-2 col-sm-2 border-0 px-lg-0 px-md-5\">\r\n");
      out.write("                    <a href=\"index.jsp\" class=\"navbar-brand me-5\">\r\n");
      out.write("                        <img src=\"logo.png\" alt=\"logo.png\">\r\n");
      out.write("                        KIMI\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"search col-lg-5 col-md-6 col-sm-6 border-0 px-lg-0 px-md-5\">\r\n");
      out.write("                    <form class=\"d-flex input-group\">\r\n");
      out.write("                        <input class=\"form-control border-0 ps-3\" type=\"text\" name=\"search\" id=\"search\"\r\n");
      out.write("                               placeholder=\"Nhập tên sản phẩm!\">\r\n");
      out.write("                        <span class=\"input-group-text  border-0\"><a class=\"nav-link\" href=\"#\"><i\r\n");
      out.write("                                class=\"fa-solid fa-magnifying-glass\"></i></a></span>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"login col-lg-2 col-md-1 col-sm-1 border-0 px-lg-0\">\r\n");
      out.write("                    <a href=\"dang_nhap.jsp\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn d-flex float-lg-end  me-xl-4 me-lg-2\">\r\n");
      out.write("                            <span class=\"d-lg-inline d-md-none d-sm-none\">Đăng nhập</span>\r\n");
      out.write("                            <span class=\"d-lg-none d-md-line material-symbols-outlined ms-1\">login</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sign-up col-lg-1 col-md-1 col-sm-1 border-0 px-lg-0\">\r\n");
      out.write("                    <a href=\"dang_ky.jsp\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn d-flex float-lg-none\">\r\n");
      out.write("                            <span class=\"d-lg-inline d-md-none  d-sm-none\">Đăng ký</span>\r\n");
      out.write("                            <span class=\"d-lg-none d-md-line material-symbols-outlined ms-1\">logout</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"cart col-lg-2 col-md-1 col-sm-1 border-0 px-lg-0\">\r\n");
      out.write("                    <a href=\"gio_hang.jsp\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn d-flex float-lg-none\">\r\n");
      out.write("                            <span class=\"d-lg-inline d-md-none  d-sm-none\">Giỏ hàng</span>\r\n");
      out.write("                            <span class=\"icon d-flex\">\r\n");
      out.write("                                <span class=\"material-symbols-outlined\">\r\n");
      out.write("                                    shopping_cart\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span id=\"amount-product\" class=\"amount-product\">\r\n");
      out.write("                                    ");

                                        CartService cart = (CartService) session.getAttribute("cart");
                                        if (cart == null) cart = new CartService();
                                    
      out.write("\r\n");
      out.write("                                    ");
      out.print(cart.getTotalProduct());
      out.write("\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"menu-product col-lg-12 col-md-1 col-sm-1\">\r\n");
      out.write("                    <!--Icon 3 dấu gạch mang hiển thị menu-->\r\n");
      out.write("                    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"offcanvas\"\r\n");
      out.write("                            data-bs-target=\"#offcanvasNavbar\"\r\n");
      out.write("                            aria-controls=\"offcanvasNavbar\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <!--Các mục trong menu-->\r\n");
      out.write("                    <div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"offcanvasNavbar\"\r\n");
      out.write("                         aria-labelledby=\"offcanvasNavbarLabel\">\r\n");
      out.write("                        <div class=\"offcanvas-body\">\r\n");
      out.write("                            <ul class=\"navbar-nav m-auto\">\r\n");
      out.write("                                <li class=\"nav-item dropdown pe-lg-5 pe-md-0\">\r\n");
      out.write("                                    <a href=\"DisplayProduct?idCategoryGroup=1&page=1\"\r\n");
      out.write("                                       class=\"nav-link dropdown-toggle px-4 rounded\"\r\n");
      out.write("                                       type=\"button\">\r\n");
      out.write("                                        <span>Kính mát</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"DisplayProduct?idCategory=1&page=1\">Kính mát\r\n");
      out.write("                                            nam</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"DisplayProduct?idCategory=2&page=1\">Kính mát\r\n");
      out.write("                                            nữ</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"DisplayProduct?idCategory=3&page=1\">Kính\r\n");
      out.write("                                            đi ngày và đêm</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"DisplayProduct?idCategory=4&page=1\">Kính đổi\r\n");
      out.write("                                            màu</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"DisplayProduct?idCategory=5&page=1\">Kính lọc ánh sáng\r\n");
      out.write("                                            xanh</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\"  href=\"DisplayProduct?idCategory=6&page=1\">Kính Mắt Clip on 2\r\n");
      out.write("                                            Lớp</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item dropdown pe-lg-5 pe-md-0\">\r\n");
      out.write("                                    <a href=\"DisplayProduct?idCategoryGroup=2&page=1\"\r\n");
      out.write("                                       class=\"nav-link dropdown-toggle px-4 rounded\" type=\"button\">\r\n");
      out.write("                                        Mắt kính trẻ em\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                                        <li><a class=\"dropdown-item\"\r\n");
      out.write("                                               href=\"DisplayProduct?idCategory=7&page=1\">Gọng Kính Trẻ Em</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\"\r\n");
      out.write("                                               href=\"DisplayProduct?idCategory=8&page=1\">Kính Mát Trẻ Em</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item dropdown pe-lg-5 pe-md-0\">\r\n");
      out.write("                                    <a href=\"DisplayProduct?idCategoryGroup=3&page=1\"\r\n");
      out.write("                                       class=\"nav-link dropdown-toggle px-4 rounded\"\r\n");
      out.write("                                       type=\"button\">\r\n");
      out.write("                                        Gọng kính\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"DisplayProduct?idCategory=9&page=1\">Gọng\r\n");
      out.write("                                            kính nữa khung</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"DisplayProduct?idCategory=10&page=1\">Gọng\r\n");
      out.write("                                            kính khoan</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"DisplayProduct?idCategory=11&page=1\">Gọng\r\n");
      out.write("                                            kính tròn</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"DisplayProduct?idCategory=12&page=1\">Gọng\r\n");
      out.write("                                            kính titan</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item dropdown pe-lg-5 pe-md-0\">\r\n");
      out.write("                                    <a href=\"DisplayProduct?idCategoryGroup=4&page=1\"\r\n");
      out.write("                                       class=\"nav-link dropdown-toggle px-4 rounded\"\r\n");
      out.write("                                       type=\"button\">\r\n");
      out.write("                                        Tròng kính\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                                        <li><a class=\"dropdown-item\"\r\n");
      out.write("                                               href=\"DisplayProduct?idCategory=13&page=1\">Tròng kính\r\n");
      out.write("                                            chống ánh sáng xanh</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"DisplayProduct?idCategory=14&page=1\">Tròng\r\n");
      out.write("                                            kính đổi màu</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"DisplayProduct?idCategory=15&page=1\">Tròng\r\n");
      out.write("                                            kính màu</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\"\r\n");
      out.write("                                               href=\"DisplayProduct?idCategory=16&page=1\">Tròng kính cho\r\n");
      out.write("                                            gọng khoan</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item dropdown pe-lg-5 pe-md-0\">\r\n");
      out.write("                                    <a href=\"DisplayProduct?idCategory=0&page=1\" class=\"menu-item nav-link px-4 rounded\">Khuyến mãi</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item dropdown pe-lg-5 pe-md-0\">\r\n");
      out.write("                                    <a href=\"lien_he.jsp\" class=\"nav-link px-4 rounded\">Liên hệ</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<main class=\"my-4 main-login\">\r\n");
      out.write("    <div class=\"modal-body form-login\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-6\">\r\n");
      out.write("                <div class=\"tab-pane fade active show\" id=\"modalLogin\" role=\"tabpanel\" aria-labelledby=\"modalLoginTab\">\r\n");
      out.write("                    <h5 class=\"text-center mb-2\">\r\n");
      out.write("                        ĐĂNG KÝ\r\n");
      out.write("                    </h5>\r\n");
      out.write("                    <div class=\"login-form-body\">\r\n");
      out.write("                        <form accept-charset=\"UTF-8\" action=\"register\" id=\"customer_login\" method=\"post\">\r\n");
      out.write("                            <input name=\"form_type\" type=\"hidden\" value=\"customer_login\">\r\n");
      out.write("                            <input name=\"utf8\" type=\"hidden\" value=\"✓\">\r\n");
      out.write("                            <div class=\"form-group mb-3\">\r\n");
      out.write("                                <label for=\"signup-fullName\">Họ và tên*</label>\r\n");
      out.write("                                <input type=\"text\" id=\"signup-fullName\" placeholder=\"Họ và tên\" class=\"form-control\"\r\n");
      out.write("                                       name=\"customer[fullName]\" required=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group mb-3\">\r\n");
      out.write("                                <div class=\"row pb-1\">\r\n");
      out.write("                                    <div class=\"col-5\"><label>Giới tính</label></div>\r\n");
      out.write("                                    <div class=\"col p-0\"><label>Ngày sinh</label></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-2 mt-1\">\r\n");
      out.write("                                        <input type=\"radio\" id=\"register-gender-0\" value=\"0\" name=\"customer[gender]\"\r\n");
      out.write("                                               checked=\"\">\r\n");
      out.write("                                        <label for=\"register-gender-0\">Nữ</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-3 mt-1\">\r\n");
      out.write("                                        <input type=\"radio\" id=\"register-gender-1\" value=\"1\" name=\"customer[gender]\"\r\n");
      out.write("                                               data-gtm-form-interact-field-id=\"0\">\r\n");
      out.write("                                        <label for=\"register-gender-1\">Nam</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"ngay_sinh col-7 p-0 d-flex\">\r\n");
      out.write("                                        <input class=\"col-2  p-1\" type=\"text\" name=\"day\" id=\"day\" placeholder=\"DD\">\r\n");
      out.write("                                        <select class=\"col-5 p-1\" name=\"month\" id=\"month\">\r\n");
      out.write("                                            <option value=\"thang 1\">Tháng 1</option>\r\n");
      out.write("                                            <option value=\"thang 2\">Tháng 2</option>\r\n");
      out.write("                                            <option value=\"thang 3\">Tháng 3</option>\r\n");
      out.write("                                            <option value=\"thang 4\">Tháng 4</option>\r\n");
      out.write("                                            <option value=\"thang 5\">Tháng 5</option>\r\n");
      out.write("                                            <option value=\"thang 6\">Tháng 6</option>\r\n");
      out.write("                                            <option value=\"thang 7\">Tháng 7</option>\r\n");
      out.write("                                            <option value=\"thang 8\">Tháng 8</option>\r\n");
      out.write("                                            <option value=\"thang 9\">Tháng 9</option>\r\n");
      out.write("                                            <option value=\"thang 10\">Tháng 10</option>\r\n");
      out.write("                                            <option value=\"thang 11\">Tháng 11</option>\r\n");
      out.write("                                            <option value=\"thang 12\">Tháng 12</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                        <input class=\"col-4  p-1\" type=\"text\" name=\"year\" id=\"year\" placeholder=\"YYYY\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group mb-3\">\r\n");
      out.write("                                <label for=\"signup-email\">Email*</label>\r\n");
      out.write("                                <input type=\"email\" id=\"signup-email\" placeholder=\"Email\" class=\"form-control\"\r\n");
      out.write("                                       name=\"customer[email]\" required=\"\">\r\n");
      out.write("                                ");
String error_email = (String) request.getAttribute("signup_error_email");
      out.write("\r\n");
      out.write("                                ");

                                    if(error_email != null){
                                
      out.write("\r\n");
      out.write("                                <small style=\"color: red\">");
      out.print(error_email);
      out.write("</small>\r\n");
      out.write("                                ");

                                    }
                                
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group  mb-3\">\r\n");
      out.write("                                <label for=\"signup-password\">Mật khẩu*</label>\r\n");
      out.write("                                <input type=\"password\" id=\"signup-password\" placeholder=\"Mật khẩu\" class=\"form-control\"\r\n");
      out.write("                                       name=\"customer[password]\" required=\"\">\r\n");
      out.write("                                ");
String error_pass = (String) request.getAttribute("signup_error_pass");
      out.write("\r\n");
      out.write("                                ");

                                if(error_pass != null){
                                
      out.write("\r\n");
      out.write("                                <small style=\"color: red\">");
      out.print(error_pass);
      out.write("</small>\r\n");
      out.write("                                ");

                                   }
                                
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group \">\r\n");
      out.write("                                <label for=\"signup-repassword\">Nhập mật khẩu*</label>\r\n");
      out.write("                                <input type=\"password\" id=\"signup-repassword\" placeholder=\"Nhập lại mật khẩu\"\r\n");
      out.write("                                       class=\"form-control\" name=\"customer[repassword]\" required=\"\">\r\n");
      out.write("                                ");

                                    if(error_pass != null){
                                
      out.write("\r\n");
      out.write("                                <small style=\"color: red\">");
      out.print(error_pass);
      out.write("</small>\r\n");
      out.write("                                ");

                                    }
                                
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group mt-2 d-flex-center\">\r\n");
      out.write("                                <button type=\"submit\" style=\"font-size: 13px;\" class=\"btn btn-primary hoverOpacity \">\r\n");
      out.write("                                    Đăng ký\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p style=\"text-align: center; font-size: 13px; margin-bottom: 2px;\" class=\"mt-2\">Hoặc</p>\r\n");
      out.write("                            <p style=\"text-align: center; font-size: 13px;\">Bạn đã có tài khoản? <a\r\n");
      out.write("                                    style=\"font-size: 13px; color: blue;\" href=\"dang_nhap.jsp\">Đăng nhập</a></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <input id=\"4acb11b585ff413fa278159c73db7b9f\" name=\"g-recaptcha-response\" type=\"hidden\"\r\n");
      out.write("                                   value=\"03AFcWeA4KJfpetZhNC6KEwIGBSiKVxBaK_FGjMxzfIlhzQgM056f9OHsepLE8lAPA_2t8bHXRmjbLqdmy3pz19RQTi4GjWJ7qB2qzBhzpLdfYUFR7nrBPnPqot6p3831ygPsCD9xJOufcQc960KZfu28-My5JLKiFC74irZ9Q26n-ttZ-JfvNYX4gWtw9sA-XAU6r_ROWClf-PZhPT2ATEeCf5YHgeLPPxGcLYleQZhLDgzSo8qmiREwucZ4_Uaw8fiG4NqKVkjtn62jS_YMyzJevJsdqu6ifcIiIe7GkrFLQD7sU64Wv4fo7TPAr9Dq-BI4nQKU_sHtUDG45z-wo4ahle6YsFfmCT9Fh_QJ7cj4feeqm2jhDtnLftPwqQSoI1L-b_B63TeOSQ2-Tr1GAE54OHMFL_YtejxRyMhFHWQHPgahGG3q9KulZsxMqly1utBkGZlg27j_bbGH4oJXwigAbTk74dQTIVrtcM_VSeNVHBsPrhoxs_S6xUtOhyBCILdpQ-r_X9nmYBvP-RcT2V6LBC7myuZG35w\">\r\n");
      out.write("                            <noscript\r\n");
      out.write("                                    data-src=\"https://www.google.com/recaptcha/api.js?render=6LdD18MUAAAAAHqKl3Avv8W-tREL6LangePxQLM-\"></noscript>\r\n");
      out.write("                            <noscript>grecaptcha.ready(function()\r\n");
      out.write("                                {grecaptcha.execute('6LdD18MUAAAAAHqKl3Avv8W-tREL6LangePxQLM-', {action:\r\n");
      out.write("                                'submit'}).then(function(token)\r\n");
      out.write("                                {document.getElementById('4acb11b585ff413fa278159c73db7b9f').value = token;});});\r\n");
      out.write("                            </noscript>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-6 banner-account\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("<hr>e\r\n");
      out.write("<footer id=\"footer\" class=\"footer\">\r\n");
      out.write("    <div class=\"container \">\r\n");
      out.write("        <div class=\"footer-top row\">\r\n");
      out.write("            <div class=\"footer-top-item col\">\r\n");
      out.write("                <h5>Mắt Kính KIMI\r\n");
      out.write("                </h5>\r\n");
      out.write("                <div class=\"footer-content footer-contact\">\r\n");
      out.write("                    <div class=\"ft_map\">\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"contact-1\"><i class=\"fa-solid fa-map-location-dot px-1\"></i><span class=\"px-1\">Khu phố 6, Phường Linh Trung, Quận Thủ Đức, TP. Hồ Chí Minh</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"contact-2\"><i class=\"fa-solid fa-phone px-1\"></i><b><span\r\n");
      out.write("                                class=\"px-1\">0855354919</span></b> ( 9:00 - 21:00 )\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"contact-3\"><i class=\"fa-solid fa-business-time px-1\"></i><span class=\"px-1\">9:00 - 20:00 ( Kể cả T7 và CN )</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"contact-4\"><i class=\"fa-solid fa-envelope px-1\"></i><span class=\"px-1\">matkinhkimi@gmail.com</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"contact-5\"><a href=\"https://www.facebook.com/profile.php?id=100045667640701\"><i\r\n");
      out.write("                                class=\"fa-brands fa-facebook-f px-1\"></i><span\r\n");
      out.write("                                class=\"px-1 hover\"><b>KIMI</b> </span></a></li>\r\n");
      out.write("                        <li class=\"contact-6\"><p>Kiểm tra thị lực miễn phí &amp; cắt kính lấy liền.</p></li>\r\n");
      out.write("                        <li class=\"contact-7\"><p>Hỗ trợ trả góp lãi suất 0% thẻ tín dụng.</p></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"footer-top-item col\">\r\n");
      out.write("                <h5>HỖ TRỢ KHÁCH HÀNG\r\n");
      out.write("                </h5>\r\n");
      out.write("                <div class=\"footer-content footer-contact\">\r\n");
      out.write("                    <div class=\"ft_map\">\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a class=\"hover\" href=\"policy_pages/huong_dan_mua_hang_online.jsp\">Hướng dẫn mua hàng online</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"hover\" href=\"policy_pages/chinh_sach_thanh_toan_va_giao_nhan.jsp\">Chính sách thanh toán,\r\n");
      out.write("                            giao nhận</a></li>\r\n");
      out.write("                        <li><a class=\"hover\" href=\"policy_pages/chinh_sach_bao_mat.jsp\">Chính sách bảo mật</a></li>\r\n");
      out.write("                        <li><a class=\"hover\" href=\"policy_pages/chinh_sach_bao_hanh.jsp\">Chính sách bảo hành</a></li>\r\n");
      out.write("                        <li><a class=\"hover\" href=\"policy_pages/chinh_sach_doi_tra_va_hoan_tien.jsp\">Chính sách đổi trả và\r\n");
      out.write("                            hoàn tiền</a></li>\r\n");
      out.write("                        <li><a class=\"hover\" href=\"policy_pages/kiem_tra_don_hang.jsp\">Kiểm tra đơn hàng</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row footer-bot text-center border-3\">\r\n");
      out.write("            <div class=\"logo col-lg-3 col-md-2 col-sm-2 border-0 px-lg-0 px-md-5\">\r\n");
      out.write("                <a href=\"index.jsp\">\r\n");
      out.write("                    <img src=\"logo.png\" alt=\"logo.png\">\r\n");
      out.write("                    <span>KIMI</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col\"><span>© 2023 - Tất cả các quyền thuộc về KIMI</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"javascript/menu_footer.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
